---
:ver: '0.1'
:host: 'localhost'
:addr: '0.0.0.0'
:ws_port: 7325
:http_port: 7326
:msgs:
  :hi: 'Привет! Отправь ''$help'', чтобы получить справку по командам.'
  :in: '%s присоединился'
  :out: '%s ушел'
  :say: '%s: %s'
  :err: 'Ошибка: %s'
  :chn: '%s сменил имя на %s'
  :ls: 'Участники: %s'
  :srv: "Сервер: %s
    \nДоступная память: %s Мб
    \nИспольуемая память: %s Мб
    \nСвободная память: %s Мб"
  :help: "Команды:
    \n$help - справка по командам
    \n$chn <to> - изменить ник на <to>
    \n$ls - список участников
    \n$srv - информация о сервере"
  
